### ISSUE TITLE
Logistic linear model trouble

### ISSUE THREAD

**Issue by ursulean** [intelligent-systems-course/planet-wars#6]
I know this isn't strictly about the code in this repo, but it's been driving me insane.

Whenever I try to build a model via train-ml-bot.py or nova-train.py by using an ml bot with an existing model (be it from a rand bot, or an alphabeta bot, or whatever) I get this error just as it finishes the last game: 

Traceback (most recent call last):
  File "nova-train.py", line 203, in <module>
    main()
  File "nova-train.py", line 66, in main
    generate_model(data, target)
  File "nova-train.py", line 74, in generate_model
    model = learner.fit(data, target)
  File "/Users/paul/anaconda/lib/python2.7/site-packages/sklearn/linear_model/logistic.py", line 1186, in fit
    sample_weight=sample_weight)
  File "/Users/paul/anaconda/lib/python2.7/site-packages/sklearn/svm/base.py", line 875, in _fit_liblinear
    " class: %r" % classes_[0])
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 'lost'

**Comment by CorralPeltzer** [comment]
This is a known problem; the bots are too passive and don't move, therefore they reach the max limits and only lose. @pbloem answered this question in the BlackBoard discussion forum.

**Comment by ursulean** [comment]
Thanks a lot
